version: "3.4"

volumes:
  db:

services:
  web:
    build:
      context: .
    depends_on:
      - db
    volumes:
      - ./example.conf:/etc/sci.conf
    command: /app/sci server
    environment:
      - SCI_DEBUG=0
      - SCI_SESSION_SECRET
      - SCI_LDAP_SERVER
      - SCI_LDAP_BIND_USER
      - SCI_LDAP_BIND_PASS
      - SCI_LDAP_BASE_DN
      - SCI_LOOKUP_BY_DUCKID_URL
      - SCI_LOOKUP_BY_BANNERID_URL
      - SCI_TRANSLATOR_API_HEADERS
      - SCI_CANVAS_API_URL
      - SCI_CANVAS_API_HEADERS

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=sci
      - MYSQL_USER=sci
      - MYSQL_PASSWORD=sci
    volumes:
      - db:/var/lib/mysql
