# This configuration is strictly for development purposes.  It doesn't
# encapsulate the Go binaries in any way, just sets up dependencies.
version: '2'

volumes:
  db:

services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=sci
      - MYSQL_USER=sci
      - MYSQL_PASSWORD=sci
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
